# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: TestApp
  template:
    metadata:
      labels:
        app: TestApp
    spec:
      containers:
        - name: Test
          image: adoptopenjdk/openjdk8:alpine-slim
          ports:
            - containerPort: 8060 # Change this to your app's port

---
apiVersion: v1
kind: Service
metadata:
  name: TestApp
spec:
  selector:
    app: Testapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8060 # Change this to match your app's port
  type: NodePort
