# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app-name
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app-name
  template:
    metadata:
      labels:
        app: your-app-name
    spec:
      containers:
        - name: your-app-container
          image: your-docker-image:tag
          ports:
            - containerPort: 8080 # Change this to your app's port

---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Change this to match your app's port
  type: NodePort
