apiVersion: apps/v1
kind: Deployment
metadata:
  name: TestApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: TestApp
  template:
    metadata:
      labels:
        app: TestApp
    spec:
      containers:
        - name: Test
          image: my-nginx-7fbf685c4d-9rnmg:harsha
          ports:
            - containerPort: 8070

---
apiVersion: v1
kind: Service
metadata:
  name: TestApp
spec:
  selector:
    app: Testapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
  type: NodePort
